package com.mpata.alquileres.models.enums;

public enum NeighborhoodCABA {
    AGRONOMIA("AGRONOMIA"),
    ALMAGRO("ALMAGRO"),
    BALVANERA("BALVANERA"),
    BARRACAS("BARRACAS"),
    BELGRANO("BELGRANO"),
    BOEDO("BOEDO"),
    CABALLITO("CABALLITO"),
    CHACARITA("CHACARITA"),
    COGHLAN("COGHLAN"),
    COLEGIALES("COLEGIALES"),
    CONSTITUCION("CONSTITUCION"),
    FLORES("FLORES"),
    FLORESTA("FLORESTA"),
    LA_BOCA("LA BOCA"),
    LA_PATERNAL("LA PATERNAL"),
    LINIERS("LINIERS"),
    MATADEROS("MATADEROS"),
    MONTE_CASTRO("MONTE CASTRO"),
    MONSERRAT("MONSERRAT"),
    NUEVA_POMPEYA("NUEVA POMPEYA"),
    NUNEZ("NUNEZ"),
    PALERMO("PALERMO"),
    PARQUE_AVELLANEDA("PARQUE AVELLANEDA"),
    PARQUE_CHACABUCO("PARQUE CHACABUCO"),
    PARQUE_CHAS("PARQUE CHAS"),
    PARQUE_PATRICIOS("PARQUE PATRICIOS"),
    PUERTO_MADERO("PUERTO MADERO"),
    RECOLETA("RECOLETA"),
    RETIRO("RETIRO"),
    SAAVEDRA("SAAVEDRA"),
    SAN_CRISTOBAL("SAN CRISTOBAL"),
    SAN_NICOLAS("SAN NICOLAS"),
    SAN_TELMO("SAN TELMO"),
    VELEZ_SARFIELD("VELEZ SARFIELD"),
    VERSALLES("VERSALLES"),
    VILLA_CRESPO("VILLA CRESPO"),
    VILLA_DEL_PARQUE("VILLA DEL PARQUE"),
    VILLA_DEVOTO("VILLA DEVOTO"),
    VILLA_GENERAL_MITRE("VILLA GENERAL MITRE"),
    VILLA_LUGANO("VILLA LUGANO"),
    VILLA_LURO("VILLA LURO"),
    VILLA_ORTUZAR("VILLA ORTUZAR"),
    VILLA_PUEYRREDON("VILLA PUEYRREDON"),
    VILLA_REAL("VILLA REAL"),
    VILLA_RIACHUELO("VILLA RIACHUELO"),
    VILLA_SANTA_RITA("VILLA SANTA RITA"),
    VILLA_SOLDATI("VILLA SOLDATI"),
    VILLA_URQUIZA("VILLA URQUIZA");

    private final String displayName;

    NeighborhoodCABA(String displayName) {
        this.displayName = displayName;
    }

    public String getValue() {
        return displayName;
    }
}